[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "droughtscan"
version = "2.0.1"
description = "Drought monitoring and seasonal prediction toolkit"
authors = [
  { name="Arianna Di Paola"},
  { name="Leandro Rocchi"},
  { name="Massimiliano Pasqui"},
]
maintainers = [
  { name="Arianna Di Paola",email="arianna.dipaola@cnr.it" }
]
readme = "README.md"
requires-python = ">=3.9"
license =  "GPL-3.0-or-later"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "cmcrameri",
    "scipy",
    "geopandas",
    "regionmask",
    "netCDF4",
    "python-dateutil",
]
[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "ruff", "black", "mypy", "pre-commit"]

[project.urls]
Homepage = "https://droughtcentral.it/"
Team = "https://droughtcentral.it/team/"

[tool.setuptools.packages.find]
where = ["."]
include = ["drought_scan*"]
exclude = ["paper*", "docs*", "tests*", "examples*"]